name:                TFG-kenflohua
version:             0.1.0.0
github:              "githubuser/TFG-kenflohua"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TFG-kenflohua#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- ffmpeg-light
- repa
- containers
# - lens
# - fixed-vector
# - monad-parallel
# - JuicyPixels-repa
# - JuicyPixels-util

library:
  source-dirs: src

executables:
  TFG-kenflohua-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TFG-kenflohua

tests:
  TFG-kenflohua-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TFG-kenflohua
