name:                TFG-kenflohua
version:             0.1.0.0
github:              "kennyfh/TFG-kenflohua"
license:             BSD3
author:              "Kenny Flores"
maintainer:          "kenflohua@alum.us.es"
copyright:           "2022 Kenny Flores"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kennyfh/TFG-kenflohua/blob/main/README.md>

dependencies:
# Modulo base
- base >= 4.7 && < 5
# Modulo para leer imagenes en un formato standard
- JuicyPixels
# Modulo que nos permite leer videor y transformarlo en imagenes
- ffmpeg-light
# Modulo que nos permite procesar arrays paralelizando CPU
- repa
# Modulo para la estructura de datos : Sequence 
- containers
# Modulo para importar tiempo (NO funciona muy bien o se está usando mal)
# - timeit
# Modulo para paralelizar elementos
- parallel
# Estructura de datos 
- vector
- accelerate
- accelerate-llvm-ptx
# Nos permite leer imagenes de juicypixels
- accelerate-io-JuicyPixels
# Nos permite transformar datos de Accelerate a Repa y viceversa
- accelerate-io-repa
# COMENTAR CUANDO ESTEMOS HACIENDO PRUEBAS EN CENTOS
#- gtk2hs-buildtools
#- gtk


library:
  source-dirs: src

executables:
  TFG-kenflohua-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    - --make
    dependencies:
    - TFG-kenflohua

tests:
  TFG-kenflohua-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TFG-kenflohua
